[package]
name = "hltas-cpp-bridge"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
hltas = { path = ".." }
nom = "5.0.1"
