[package]
name = "hltas-cpp-bridge"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
hltas = { path = ".." }
nom = "7.1.3"
cfg-if = "1.0.0"
