[package]
name = "hltas-rs"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
nom = "5.0.1"

[[bin]]
name = "parse"
path = "src/bin/parse.rs"
