name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *' # Monthly

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        label:
          - Linux
          - Windows
          - macOS

        include:
          - label: Linux
            os: ubuntu-latest
            target: i686-unknown-linux-gnu

          - label: Windows
            os: windows-latest
            target: i686-pc-windows-msvc

          - label: macOS
            os: macOS-latest

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Install g++-multilib
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install g++-multilib

    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        targets: ${{ matrix.target }}

    - name: Test the Rust crate
      run: |
        cargo build
        cargo test

    - name: Test the Rust-C++ bridge
      run: |
        cd hltas-cpp-bridge
        cargo test

    - name: Test the Rust-C++ bridge on ${{ matrix.target }}
      if: matrix.target != ''
      run: |
        cd hltas-cpp-bridge
        cargo test --target=${{ matrix.target }}

    - name: Generate the C++ build system
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build the C++ library
      run: cmake --build build

    - name: Test the C++ library
      run: |
        cd build
        ctest --output-on-failure
