name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Test the Rust crate
      run: |
        cargo build
        cargo test

    - name: Generate the C++ build system
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build the C++ library
      run: cmake --build build

    - name: Test the C++ library
      run: |
        cd build
        ctest --output-on-failure
